[project]
name = "raylm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "lancedb>=0.25.3",
    "openai>=2.7.2",
    "pillow>=12.0.0",
    "pypdfium2>=5.0.0",
    "ray>=2.51.1",
    "requests>=2.32.5",
]
